plugins:
  - ./plugins/medusa/index.js
decorators:
  medusa/circular-patch:
    schemas:
      GiftCardTransaction:
        - GiftCard
        - Order
      LineItemAdjustment:
        - LineItem
      LineItemTaxLine:
        - LineItem
      CustomerGroupResponse:
        - CustomerResponse
      ProductCategoryResponse:
        - ProductCategoryResponse
      AdminShippingOption:
        - AdminShippingOption
        - AdminServiceZone
      AdminProductCategory:
        - AdminProductCategory
        - AdminProduct
      BaseProduct:
        - BaseProduct
      StoreProduct:
        - StoreProductCategory
        - StoreProduct
      AdminCollection:
        - AdminProduct
      AdminProduct:
        - AdminProduct
      AdminStockLocation:
        - AdminFulfillmentSet
      OrderChange:
        - Order
      StoreShippingOption:
        - StoreShippingOption
      AdminServiceZone:
        - AdminFulfillmentSet
      OrderTransaction:
        - Order
      AdminTaxRegion:
        - AdminTaxRegion
        - AdminTaxRate
      AdminInventoryLevel:
        - AdminInventoryItem
theme:
  openapi:
    theme:
      colors:
        primary:
          dark: '#242526'
      sidebar:
        width: 250px
    disableSearch: true
    expandResponses: 200,204
    generatedPayloadSamplesMaxDepth: 4
    hideDownloadButton: true
    hideRequestPayloadSample: true
    nativeScrollbars: true
    requiredPropsFirst: true
    showObjectSchemaExamples: true
    sortTagsAlphabetically: true
