name: Update on RC Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ contains(github.event.release.tag_name, 'rc') }}
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.STARTER_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/medusajs/medusa-starter-default/actions/workflows/update-preview-deps.yml/dispatches \
          -d '{"ref":"master"}'
  generate-references:
    uses: ./.github/workflows/generate-preview-references.yml